version: "3.8"
services:
    zookeeper:
        container_name: zookeeper
        image: bitnami/zookeeper
        ports:
            - 2181:2181
        networks: 
            - microservice1
        environment: 
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        container_name: kafka
        image: bitnami/kafka
        ports:
            - 9092:9092
        networks: 
            - microservice1
        environment: 
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        depends_on: 
            - zookeeper
    
networks:
    microservice1:
        name: microservice1