version: "3.8"
services:
    zookeeper:
        container_name: zookeeper
        image: bitnami/zookeeper
        ports:
            - 2181:2181
        environment: 
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks: 
            - microservice_app
    kafka:
        container_name: kafka
        image: bitnami/kafka
        ports:
            - 9092:9092
        environment: 
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        networks: 
            - microservice_app
        depends_on: 
            - zookeeper
networks:
    microservice_app:
        name: microservice_app
